### PR TITLE
Fixed lifecycle issue when using the plugin in a single file componen…

### PR DESCRIPTION
**Pull request by 51fe**
Fixed issue: Error in created hook: "TypeError: Cannot read property 'subscribe' of undefined"

### CODE REVIEW

**Comment by 51fe** [comment]
@anthonygore Hi, I found a lifecycle issue when running https://codesandbox.io/s/vjo3xlpyny and fixed it, please confirm it.

**Review by caugner — APPROVED** [review]
Looks good to me

**Comment by anthonygore** [comment]
Sorry for the delay.

Can you explain why `this.$store.subscribe` is undefined in the created hook? If the Vuex plugin is already installed, it should be available in the created hook since that's when reactive data and observation has been setup. What made you change to the mounted hook and why does that work? I don't get it!

**Comment by anthonygore** [comment]
Okay I get it now.

So the issue in your code sandbox is that the VuexUndoRedo plugin was being installed in your store file. I know it's conufsing, but this plugin is actually a Vue plugin, not a Vuex plugin!

I've gotten your code working by simply installing the plugin after the Vuex store gets created in the main app file. It works fine after that. Here's a demo:

https://codesandbox.io/s/qqrj2v9xv6

I'll close this PR as I don't think moving the code to the mounted hook is the correct solition. I think I'm going to instead throw an error if the user attempts to install the plugin before their Vuex store is created.

Thanks for taking the time to provide this PR.

**Pull request closed without merging**
